language: android

jdk:
- oraclejdk8
- openjdk11

before_install:
# Install SDK license so Android Gradle plugin can install deps.
- mkdir "$ANDROID_HOME/licenses" || true
- echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > "$ANDROID_HOME/licenses/android-sdk-license"
- echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" >> "$ANDROID_HOME/licenses/android-sdk-license"

install: ./gradlew assemble
script: ./gradlew build

branches:
  except:
  - gh-pages

notifications:
  email: false
  
